version: '3'
services:
  app:
    image: ${ORG_NAME}/${APP_NAME}:dev
    container_name: ${APP_NAME}
    env_file:
      - ../../.env
    restart: on-failure
    volumes:
       - ../../cert:/cert
       - ../../src:/go/src/${ORG_NAME}/${APP_NAME}/src
       - ../../pkg:/go/src/${ORG_NAME}/${APP_NAME}/pkg
       - ../../vendor:/go/src/${ORG_NAME}/${APP_NAME}/vendor
    networks:
      - web
    labels:
      - "traefik.protocol=https"
      - "traefik.backend=${APP_NAME}"
      - "traefik.frontend.rule=Host:${APP_NAME}.${DOMAIN}"
      - "traefik.priority=10"

networks:
  web:
    external:
      name: awpc_webgateway