version: '3'
services:
  app:
    image: ${ORG_NAME}/${APP_NAME}:dev
    container_name: ${APP_NAME}
    env_file:
      - ../../.env
    restart: on-failure
    volumes:
       - ../../src:/go/src/${ORG_NAME}/${APP_NAME}/src
    networks:
      - web
    labels:
      - "traefik.protocol=https"
      - "traefik.backend=${APP_NAME}"
      - "traefik.frontend.rule=Host:${APP_NAME}.<%= apiUrl %>"
      - "traefik.priority=10"

networks:
  web:
    external:
      name: awpc_webgateway